import type { Product } from "../types/product";

const DEFAULT_DESCRIPTION = "Explore a breathtaking world, engage in intense combat, and uncover the truth behind a mercenary's destiny. Experience high-quality graphics and immersive gameplay in this next-generation title.";
const DEFAULT_COUNTRIES = ["Brazil", "Portugal", "USA", "Germany", "Japan", "Canada", "Australia", "United Kingdom"];

export const mockProducts: Product[] = [
  { 
    id: "1", 
    name: "Human: Fall Flat Steam Key LATAM", 
    image: "", 
    platform: "Steam", 
    price: 10.99, 
    originalPrice: 17.99, 
    genre: "Adventure",
    region: "LATAM",
    rating: 4.8,
    reviewsCount: 1500,
    description: "Human: Fall Flat is a hilarious, light-hearted physics platformer set in floating dreamscapes that can be played solo or with up to 8 players online.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["Brazil", "Argentina", "Chile", "Mexico", "Colombia"],
    stockStatus: "10+ in stock"
  },
  { 
    id: "2", 
    name: "Capote Steam(PC) Key LATAM", 
    image: "", 
    platform: "Steam", 
    price: 8.99, 
    originalPrice: 11.99, 
    genre: "Adventure",
    region: "LATAM",
    rating: 4.2,
    reviewsCount: 85,
    description: "A mysterious adventure game where every choice matters. Uncover the secrets of a forgotten city.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["Brazil", "Argentina", "Peru"],
    stockStatus: "5 in stock"
  },
  { 
    id: "3", 
    name: "Ori and the Blind Forest (Definitive Edition) Steam (PC) Key GLOBAL", 
    image: "", 
    platform: "Steam", 
    price: 22.99, 
    originalPrice: 39.9, 
    genre: "Adventure",
    region: "GLOBAL",
    rating: 5.0,
    reviewsCount: 12500,
    description: "The forest of Nibel is dying. After a powerful storm sets a series of devastating events in motion, Ori must journey to find courage and confront a dark nemesis to save the forest of Nibel.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["All Countries"],
    stockStatus: "Unlimited"
  },
  { 
    id: "4", 
    name: "HumanitZ Steam Key LATAM", 
    image: "", 
    platform: "Steam", 
    price: 10.99, 
    originalPrice: 17.99, 
    genre: "Simulation",
    region: "LATAM",
    rating: 4.5,
    reviewsCount: 320,
    description: "HumanitZ is a top-down, open-world survival game in a world ended by the zombie outbreak. As one of the few human survivors, try to last as long as 'humanly' possible.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["Brazil", "Chile", "Uruguay"],
    stockStatus: "8 in stock"
  },
  { 
    id: "5", 
    name: "Crimson Desert Deluxe Edition Steam Key LATAM", 
    image: "", 
    platform: "Steam", 
    price: 245.99, 
    originalPrice: 299.99, 
    genre: "Action",
    region: "LATAM",
    rating: 4.9,
    reviewsCount: 128,
    description: "Crimson Desert is an open-world action-adventure game set in the vast continent of Pywel. Explore a breathtaking world, engage in intense combat, and uncover the truth behind a mercenary's destiny.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["Belize", "El Salvador", "Honduras", "Brazil", "Guatemala", "Panama", "Costa Rica", "Nicaragua"],
    stockStatus: "5+ in stock"
  },
  { 
    id: "6", 
    name: "Elden Ring Steam Key GLOBAL", 
    image: "", 
    platform: "Steam", 
    price: 129.99, 
    originalPrice: 199.99, 
    genre: "RPG",
    region: "GLOBAL",
    rating: 5.0,
    reviewsCount: 45000,
    description: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["All Countries"],
    stockStatus: "20+ in stock"
  },
  { 
    id: "7", 
    name: "Call of Duty: Modern Warfare II Steam Key GLOBAL", 
    image: "", 
    platform: "Steam", 
    price: 149.99, 
    originalPrice: 249.99, 
    genre: "Action",
    region: "GLOBAL",
    rating: 4.7,
    reviewsCount: 8900,
    description: "Call of Duty: Modern Warfare II drops players into an unprecedented global conflict that features the return of the iconic operators of Task Force 141.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["All Countries"],
    stockStatus: "15 in stock"
  },
  { 
    id: "8", 
    name: "Forza Horizon 5 Steam Key GLOBAL", 
    image: "", 
    platform: "Steam", 
    price: 99.99, 
    originalPrice: 179.99, 
    genre: "Racing",
    region: "GLOBAL",
    rating: 4.9,
    reviewsCount: 15600,
    description: "Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars.",
    type: "Key",
    delivery: "Instant Delivery",
    allowedCountries: ["All Countries"],
    stockStatus: "12 in stock"
  },
];
